# Generated by Django 4.2.16 on 2026-06-11 16:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Deletado')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descrição')),
                ('start_date', models.DateField(verbose_name='Data de início')),
                ('end_date', models.DateField(verbose_name='Data de fim')),
                ('status', models.CharField(choices=[('not_started', 'Não Iniciada'), ('in_progress', 'Em Progresso'), ('done', 'Concluída')], default='not_started', max_length=15, verbose_name='Status')),
                ('tasks', models.ManyToManyField(blank=True, related_name='sprints', to='tasks.task', verbose_name='Tarefas')),
            ],
            options={
                'verbose_name': 'Sprint',
                'verbose_name_plural': 'Sprints',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Deletado')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descrição')),
                ('status', models.CharField(choices=[('paused', 'Pausado'), ('active', 'Ativo'), ('done', 'Concluído'), ('closed', 'Encerrado')], default='active', max_length=10, verbose_name='Status')),
                ('current_sprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_in_projects', to='projects.sprint', verbose_name='Sprint atual')),
                ('sprints', models.ManyToManyField(blank=True, related_name='projects', to='projects.sprint', verbose_name='Sprints')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
